In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [23]:
np.mean(iris.data, axis=0) # 5.5, 2.9, 3.4, 0.9

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [25]:
np.unique(iris.target), iris.target_names

(array([0, 1, 2]), array(['setosa', 'versicolor', 'virginica'], dtype='<U10'))

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split(iris.data, iris.target, random_state=42)

In [26]:
X_test[:5], y_test[:5]

(array([[6.1, 2.8, 4.7, 1.2],
        [5.7, 3.8, 1.7, 0.3],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.9, 4.5, 1.5],
        [6.8, 2.8, 4.8, 1.4]]),
 array([1, 0, 2, 1, 1]))

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
rf_model = RandomForestClassifier(n_estimators=50, max_depth=4, random_state=42)

rf_model.fit(X_train, y_train)

rf_model.score(X_train, y_train), rf_model.score(X_test, y_test)

(1.0, 1.0)

In [17]:
import pickle

with open("iris_estimator.pkl", "wb") as f:
    pickle.dump(rf_model, f)

In [18]:
with open('iris_estimator.pkl', 'rb') as f:
    rf_model2 = pickle.load(f)

In [19]:
rf_model2.score(X_test, y_test)

1.0

In [28]:
X_train.shape

(112, 4)